name: ffmpeg
version: 0
summary: This is meant to be consumed by other projects
description: |
  This sets up ffmpeg for projects.

parts:
  ffmpeg:
    build-packages:
    - libass-dev
    - libfreetype6-dev
    - libmp3lame-dev
    - libopus-dev
    - libsdl1.2-dev
    - libtheora-dev
    - libva-dev
    - libvdpau-dev
    - libvorbis-dev
    - libvpx-dev
    - libx264-dev
    - libx265-dev
    - libxcb1-dev
    - libxcb-shm0-dev
    - libxcb-xfixes0-dev
    - pkg-config
    - texinfo
    - yasm
    - zlib1g-dev
    plugin: autotools
    configflags:
    - --prefix=/
    - --enable-gpl
    - --enable-libass
    - --enable-libfreetype
    - --enable-libmp3lame
    - --enable-libopus
    - --enable-libtheora
    - --enable-libvorbis
    - --enable-libvpx
    - --enable-libx264
    - --enable-libx265
    - --enable-nonfree
    source: git://source.ffmpeg.org/ffmpeg.git
    source-type: git
    source-branch: release/3.4
    source-depth: 1
    stage-packages:
    - libasound2
    - libass5
    - libdrm2
    - libfontconfig1
    - libfribidi0
    - libgraphite2-3
    - libharfbuzz0b
    - libmp3lame0
    - libnuma1
    - libogg0
    - libopus0
    - libtheora0
    - libva-drm1
    - libva-x11-1
    - libva1
    - libvdpau1
    - libvorbis0a
    - libvorbisenc2
    - libvpx3
    - libx11-6
    - libx264-148
    - libx265-79
    - libxau6
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-xfixes0
    - libxdmcp6
    - libxext6
    - libxfixes3

    filesets:
      docs:
      - share/doc

      docs-copyright:
      - usr/share/doc/*/copyright

      docs-examples:
      - share/ffmpeg/examples/*

      docs-manpages:
      - share/man/*

      executables:
      - bin/*
      - usr/bin/*

      library-headers:
      - include/*

      library-pkgconfig:
      - lib/pkgconfig/*

      library-shared:
      - lib/**/*.so*
      - usr/lib/**/*.so*

      library-static:
      - lib/**/*.a
      - usr/lib/**/*.a

      misc:
      - etc/*
      - usr/share/alsa/*
      - usr/share/bug/*
      - usr/share/fonts/*
      - usr/share/libdrm/*
      - usr/share/lintian/*
      - usr/share/man/*
      - usr/share/X11/*

    stage:
    - $docs-copyright
    - $library-headers
    - $library-pkgconfig
    - $library-shared
    - $library-static

    prime:
    - $docs-copyright
    - $library-shared

